import type { Metadata } from 'next'
import { Syne, Smooch } from 'next/font/google'
import './globals.css'
import MainNav from './components/UI/MainNav'

const syne = Syne({ 
  subsets: ['latin'], 
  weight: ['400','500','600','700','800'],
  variable: '--font-syne' 
})

const smooch = Smooch({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-smooch'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${smooch.variable}`}>
        <MainNav />
        {children}
      </body>
    </html>
  )
}
